[build]
rustflags = ["-Dwarnings"]

[target.'cfg(all())']
rustflags = ["-Dwarnings"]

[alias]
check-clippy = "clippy --all-targets --all-features -- -D warnings"

[profile.dev]
opt-level = 2
debug = 1
lto = "thin"
codegen-units = 8

[profile.test]
inherits = "dev"
opt-level = 3
lto = "thin"

[env]
RUSTFLAGS = "-C target-cpu=native"
QUICKCHECK_TESTS = "5"

